name: Publish Docker image

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow when a tag like v1.0.0 is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract tag version
        id: extract_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Build and push Docker image with version tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: miguelmartens/ticketkantoor-event-scraper:${{ steps.extract_version.outputs.VERSION }}

      - name: Build and push Docker image with latest tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: miguelmartens/ticketkantoor-event-scraper:latest
